# Generated by Django 4.2.6 on 2023-11-15 11:43

import datetime
import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('cover', models.FileField(blank=True, null=True, upload_to='files/property_cover/car')),
                ('description', models.CharField(max_length=512)),
                ('color', models.CharField(blank=True, max_length=128, null=True)),
                ('dateModel', models.CharField(blank=True, max_length=128, null=True)),
                ('brand', models.CharField(blank=True, max_length=128, null=True)),
                ('price', models.CharField(blank=True, max_length=128, null=True)),
                ('motorStation', models.CharField(blank=True, max_length=128, null=True)),
                ('gearbox', models.CharField(blank=True, max_length=128, null=True)),
                ('operation', models.CharField(blank=True, max_length=128, null=True)),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('ownersPhone', models.CharField(max_length=11)),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('cover', models.FileField(blank=True, null=True, upload_to='files/property_cover/home')),
                ('description', models.CharField(max_length=512)),
                ('meterage', models.CharField(max_length=128)),
                ('constructedDate', models.CharField(max_length=128)),
                ('rooms', models.CharField(max_length=128)),
                ('homeType', models.CharField(blank=True, choices=[('sell', 'فروش'), ('rent', 'رهن و اجاره')], max_length=60, null=True)),
                ('attributes', multiselectfield.db.fields.MultiSelectField(choices=[('elevator', 'آسانسور'), ('parking', 'پارکینگ'), ('houseware', 'انباری'), ('master', 'اتاق خواب مستر'), ('yard', 'حیاط')], max_length=60)),
                ('price', models.CharField(blank=True, max_length=128, null=True)),
                ('pricePerMeter', models.CharField(blank=True, max_length=128, null=True)),
                ('mortgage', models.CharField(blank=True, max_length=128, null=True)),
                ('rent', models.CharField(blank=True, max_length=128, null=True)),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('ownersPhone', models.CharField(max_length=11)),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('cover', models.FileField(blank=True, null=True, upload_to='files/property_cover/other')),
                ('description', models.CharField(max_length=512)),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('ownersPhone', models.CharField(max_length=11)),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
