# Generated by Django 4.2.6 on 2023-11-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='other',
            name='price',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
