# Generated by Django 4.2.6 on 2023-11-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_other_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='address',
            field=models.CharField(default='test', max_length=256),
        ),
        migrations.AddField(
            model_name='home',
            name='address',
            field=models.CharField(default='test', max_length=256),
        ),
        migrations.AddField(
            model_name='other',
            name='address',
            field=models.CharField(default='test', max_length=256),
        ),
    ]
