# Generated by Django 4.2.6 on 2023-11-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_car_address_home_address_other_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='files/property_cover/car'),
        ),
        migrations.AlterField(
            model_name='home',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='files/property_cover/home'),
        ),
        migrations.AlterField(
            model_name='other',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='files/property_cover/other'),
        ),
    ]
